CREATE TABLESPACE DATA 
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\DATA.DBF'
SIZE 100M
AUTOEXTEND ON NEXT 50M MAXSIZE 500M;

-- Puis créer une table dans ce tablespace :
CREATE TABLE ma_table (
    id NUMBER PRIMARY KEY,
    nom VARCHAR2(50)
) TABLESPACE DATA;

ALTER DATABASE DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\USERS.DBF' RESIZE 100M;
